import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer";
import { ThemeProvider } from "@/context/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EduGang",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <ThemeProvider>
        <html lang="en">
        <body className="bg-gray-100">
          <Navbar />
          <main className="max-w-7xl mx-auto">
           {children}
          </main>
          <Footer />
        </body>
      </html>
    </ThemeProvider>
    </ClerkProvider>
  );
}
